force-app/main/default/objects/Krow_Project__c/Krow_Project__c.object-meta.xml
<CustomObject>
    <label>Krow Project</label>
    <nameField>
        <displayFormat>K-{000}</displayFormat>
        <label>Krow Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Krow Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Krow_Project__c/fields/isTemplateKrow__c.field-meta.xml
<CustomField>
    <fullName>isTemplateKrow__c</fullName>
    <formula>ISPICKVAL(Onboarding_Type__c, &quot;Template&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isTemplateKrow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Krow_Project__c/fields/Onboarding_Type__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Type__c</fullName>
    <label>Onboarding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Onboarding</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Krow_Project__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Krow Projects</relationshipLabel>
    <relationshipName>Krow_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Krow_Task__c/Krow_Task__c.object-meta.xml
<CustomObject>
    <label>Krow Task</label>
    <nameField>
        <label>Krow Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Krow Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Krow_Task__c/fields/Krow_Project__c.field-meta.xml
<CustomField>
    <fullName>Krow_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Krow Project</label>
    <referenceTo>Krow_Project__c</referenceTo>
    <relationshipLabel>Krow Tasks</relationshipLabel>
    <relationshipName>Krow_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Krow_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>Mobile Data Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderTriggerKrowTest.cls
@isTest
public class OrderTriggerKrowTest {
    @isTest
    static void testOrderActivation() {
        Account acc = new Account(Name='Test Account');
        insert acc;
        
        Contract CC = New Contract();
        CC.Accountid = acc.id;
        CC.Status = 'Draft';
        CC.StartDate = Date.today();
        CC.ContractTerm = 2;
        Insert CC;
        CC.Status = 'Activated';
        update CC;
        
        Opportunity opp = new Opportunity(Name='Test Opportunity', StageName='Prospecting', CloseDate=Date.today(), AccountId=acc.Id,Services__c='test');
        insert opp;
        Product2 prod = new Product2(Name = 'Laptop X200', 
                                     Family = 'Hardware',price__c=120);
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
        
        Krow_Project__c kc = new Krow_Project__c();
        kc.Onboarding_Type__c='Template';
        insert kc;
        Krow_Task__c ktc = new Krow_Task__c();
        ktc.Krow_project__c=kc.Id;
        insert ktc;
        
        Order ord = new Order(Name='Test Order', EffectiveDate=Date.today(), Status='Draft', AccountId=acc.Id, OpportunityId=opp.Id,contractid=CC.id,Pricebook2Id = customPB.Id);
        insert ord;
        OrderItem oi = new OrderItem(OrderId=ord.Id, PricebookEntryId=customPrice.Id, 
                                     Quantity=2, UnitPrice=100.00, Product2Id = prod.Id);
        insert oi;
        ord.OrderItems.add(oi);
        opp.StageName = 'Signature';
        update opp;
        ord.Status = 'Activated';
        update ord;
        
        List<Krow_Project__c> krowProjects = [SELECT Id, Onboarding_Type__c FROM Krow_Project__c WHERE Order__c = :ord.Id];
        System.assertEquals(1, krowProjects.size());
        System.assertEquals('Installation', krowProjects[0].Onboarding_Type__c);
        System.debug(krowProjects);
        
        List<Krow_Task__c> krowTasks = [SELECT Id,Name,Status__c FROM Krow_Task__c WHERE Krow_Project__r.isTemplateKrow__c=true];
        System.assertNotEquals(0, krowTasks.size());
        
        try {
            update ord;
            System.assert(false, 'Expected error did not occur');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains('Cannot mark Order as Completed if Opportunity Stage is not Signature.'));
        }
    }
}