force-app/main/default/objects/Krow_Project__c/Krow_Project__c.object-meta.xml
<CustomObject>
    <label>Krow Project</label>
    <nameField>
        <displayFormat>K-{000}</displayFormat>
        <label>Krow Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Krow Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Krow_Project__c/fields/Onboarding_Type__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Type__c</fullName>
    <label>Onboarding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Onboarding</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Krow_Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Krow Projects</relationshipLabel>
    <relationshipName>Krow_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>Mobile Data Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppTriggerKrowTest.cls
@isTest
public class OppTriggerKrowTest {
    @isTest
    static void testOppTriggerKrow() {
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today(),
            Services__c='test'
        );
        insert opp;
        List<Krow_Project__c> krowsBefore = [SELECT Id, Onboarding_Type__c, Opportunity__c FROM Krow_Project__c];
        System.assertEquals(0, krowsBefore.size());
        
        opp.StageName = 'Signature';
        update opp;
        List<Krow_Project__c> krowsAfter = [SELECT Id, Onboarding_Type__c,Opportunity__c FROM Krow_Project__c];
        System.assertEquals(1, krowsAfter.size());
        System.assertEquals('Customer Onboarding', krowsAfter[0].Onboarding_Type__c);
        System.assertEquals(opp.Id, krowsAfter[0].Opportunity__c);
    }
}