force-app/main/default/objects/Account/fields/Is_Gold__c.field-meta.xml
<CustomField>
    <fullName>Is_Gold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Gold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>Mobile Data Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateAccountIsGoldTest.cls
@isTest
public class UpdateAccountIsGoldTest {
    @isTest
    static void testUpdateAccountIsGold() {
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        Opportunity opp1 = new Opportunity(AccountId = acc.Id, Name = 'Test Opportunity 1', Amount = 10000 , StageName ='Check',CloseDate = System.today(),Services__c='Fixed');
        insert opp1;
        acc = [SELECT Id, Is_gold__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(false, acc.Is_gold__c);
        Opportunity opp2 = new Opportunity(AccountId = acc.Id, Name = 'Test Opportunity 2', Amount = 25000, StageName ='Check',CloseDate = System.today(),Services__c='Fixed');
        insert opp2;
        acc = [SELECT Id, Is_gold__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(true, acc.Is_gold__c);
    }
}