force-app/main/default/objects/student__c/student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/student__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Student</relationshipLabel>
    <relationshipName>Student</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/student__c/fields/Fee_Status__c.field-meta.xml
<CustomField>
    <fullName>Fee_Status__c</fullName>
    <label>Fee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Defaulter</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentTriggerCaseTest.cls
@isTest
public class StudentTriggerCaseTest {
    @isTest
    static void testStudentTriggerCase(){
        student__c student = new student__c();
        student.Name='Student';
        student.Fee_Status__c='Defaulter';
        insert student;
        
        List<Case> cases = [SELECT Subject FROM Case WHERE Subject='Defaulter Student'];
        System.assertEquals(1, cases.size());
        
        student__c studentAfterInsert = [SELECT Case_Number__c FROM student__c WHERE Id =: student.Id];
        System.assertNotEquals(null, studentAfterInsert.Case_Number__c);
    }
}