force-app/main/default/objects/Opportunity/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>ICT</fullName>
            </value>
            <value>
                <fullName>Mobile Data Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTriggerTest.cls
@isTest
public class OpportunityLineItemTriggerTest {
    @isTest
    static void OpportunityLineItemTrigger(){
        Product2 pro = new Product2(
            Name = 'Test Product',
            Family = 'Test Family',
            Price__c=123.23
        );
        insert pro;
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Test StageName',
            CloseDate = Date.today(),
            Services__c = 'Test Family'
        );
        insert opp;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Product2Id = pro.Id,
            Quantity = 1,
            PricebookEntryId = Test.getStandardPriceBookId()
        );
        Test.startTest();
        insert oli;
        Test.stopTest();
        
        List<OpportunityLineItem> oliList = [SELECT Id FROM OpportunityLineItem WHERE OpportunityId = :opp.Id];
        System.assertEquals(1, oliList.size());
    }
}